### Read all movies with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films

### Read all movies in function of minimum-duration

GET {{baseUrl}}/films/?minimum-duration=120

### Read one movie identifies by an id
GET {{baseUrl}}/films/1

### Create a new movie
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title":"blablabla",
    "duration":100,
    "budget":1000000,
    "link":"link"
}